### PR TITLE
Fix typo in README.md

### PR DESCRIPTION
**Pull request by MaxDesiatov**

### CODE REVIEW

**Comment by akkyie** [comment]
@MaxDesiatov Thanks! Are you interested in being a collaborator of this repo?

**Comment by MaxDesiatov** [comment]
@akkyie That would be fantastic, I'm deeply grateful for the offer!

**Comment by akkyie** [comment]
@MaxDesiatov Pleasure is mine! Sent an invitation.

**Comment by MaxDesiatov** [comment]
@akkyie got it, thanks again! 

I know there are enough WebAssembly runtime implementations out there, though none of those are in Swift, nevertheless it's probably going to be hard to compete with something like [wasm3](https://github.com/wasm3/wasm3) or `wasm-interp` from [wabt](https://github.com/WebAssembly/wabt) with our limited resources.. I'm myself mainly interested in developing WAKit for educational purposes to get a better understanding of how WebAssembly works. I'd be happy though if anyone considers embedding WAKit into their applications and would like to support that if any demand for it appears. 

One of the goals I see is slowly making it fully compatible with the spec, and also portable across different platforms, supporting Linux and possibly Windows, when Swift's support for Windows is mature enough. I'm thinking adding a GitHub Actions workflow for Linux as a first attempt, and maybe migrating macOS/iOS builds to GitHub Actions from Bitrise, if that seems reasonable to you?

What development style would you prefer for this? Would you like me to create a PR for every change requesting a review from you, or would you prefer to be less involved (I understand you have a few other projects that you're working on) with less disruptive changes going to `master` or feature branches directly, with yourself reviewing only risky changed and PRs from other people?

**Comment by akkyie** [comment]
@MaxDesiatov It's exactly what I was thinking when I start this project, not to compete other fast/efficient runtimes but to learn how WebAssembly VMs works. That's why I wanted it to be pure Swift interpreter and keep a readable codebase.

As you said, I'm not sure how I can take time to keep contributing to this project now, so I don't make myself a barrier against your development. Until it becomes _minimum valuable_ at least, I'm not worried about you make changes to master directly.
And yes, using GitHub Actions sounds the best choice now.

That said, welcoming committers like you to my own project is undeniably a big motivation for me to start maintaining it again. I'll find time to remember what I was doing here first :)

**Pull request merged**
